import type { Metadata } from 'next'
import { Montserrat } from 'next/font/google'
import './globals.css'
import MetaTags from "@/app/metatags";

const font = Montserrat({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Vojtěch Váchal',
  description: 'Portfolio app about Vojtěch Váchal. Software developer. Generated by create next app.',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
    <MetaTags />
    <body className={font.className}>{children}</body>
    </html>
  )
}
